name: Daily Newspaper Email

on:
  schedule:
    - cron: '30 14 * * *'  # 7:30 AM PST
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser jinja2 python-dotenv

      - name: Debug file structure
        run: |
          echo "Current directory:"
          pwd
          echo "List all files:"
          ls -R
          echo "Show contents of newspaper.py:"
          cat newspaper.py || echo "newspaper.py not found!"

      - name: Run newspaper script
        run: python newspaper.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
